/**
 * Algorithm Fusion Tests — Kill the Ring
 *
 * These tests validate the fusion engine (fuseAlgorithmResults) against
 * synthetic scenarios generated by Gemini Ultra's vulnerability analysis.
 * Each scenario constructs an algorithm score vector that represents a
 * specific real-world audio situation and asserts the expected verdict.
 *
 * Test categories:
 *   1. Weight summation validation
 *   2. Effective weights when comb is absent
 *   3. Single-algorithm isolation (no single algo reaches FEEDBACK)
 *   4. Gemini's 8 vulnerability scenarios (current weights)
 *   5. Three-model consensus vulnerability scenarios (TEST-004)
 *   6. Pure feedback / pure music / pure noise baselines
 *   7. Edge cases (single algorithm, warmup, null scores)
 *   8. Proposed V2 weights (regression tests for improved weights)
 *
 * References:
 *   - algorithmFusion.ts: fuseAlgorithmResults(), FUSION_WEIGHTS
 *   - Gemini Ultra vulnerability analysis (March 2026)
 *   - Deep Algorithm Audit findings DA-004 (confidence warmup penalty)
 */

import { describe, it, expect } from 'vitest'
import {
  fuseAlgorithmResults,
  FUSION_WEIGHTS,
  DEFAULT_FUSION_CONFIG,
  type FusionConfig,
} from '@/lib/dsp/algorithmFusion'
import { buildScores, type ScoreInput } from '../helpers/mockAlgorithmScores'

// ── Helper ───────────────────────────────────────────────────────────────────

/** Run fusion with a simplified score input and return the result */
function fuse(
  input: ScoreInput,
  contentType: 'speech' | 'music' | 'compressed' | 'unknown' = 'unknown',
  existingScore: number = 0.5,
  config?: Partial<FusionConfig>,
  peakFrequencyHz?: number
) {
  return fuseAlgorithmResults(
    buildScores(input),
    contentType,
    existingScore,
    { ...DEFAULT_FUSION_CONFIG, ...config },
    peakFrequencyHz
  )
}

// ═════════════════════════════════════════════════════════════════════════════
// 1. WEIGHT VALIDATION
// ═════════════════════════════════════════════════════════════════════════════

describe('Fusion Weight Profiles', () => {
  it('DEFAULT weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.DEFAULT
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr + w.existing
    expect(sum).toBeCloseTo(1.0, 10)
  })

  it('SPEECH weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.SPEECH
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr + w.existing
    expect(sum).toBeCloseTo(1.0, 10)
  })

  it('MUSIC weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.MUSIC
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr + w.existing
    expect(sum).toBeCloseTo(1.0, 10)
  })

  it('COMPRESSED weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.COMPRESSED
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr + w.existing
    expect(sum).toBeCloseTo(1.0, 10)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 2. EFFECTIVE WEIGHTS WITHOUT COMB
//
// When comb pattern is absent (the common case), comb weight drops out of
// totalWeight. Each algorithm's effective share = nominal / totalNoComb.
// ═════════════════════════════════════════════════════════════════════════════

describe('Effective Weights — Comb Absent', () => {
  /**
   * For each profile, totalNoComb = 1 - combWeight.
   * Effective share = algorithmWeight / totalNoComb.
   */

  it('SPEECH MSD effective weight is 34.7% (FIX-004: reduced from 42.1%)', () => {
    const w = FUSION_WEIGHTS.SPEECH
    const totalNoComb = 1 - w.comb
    const effectiveMsd = w.msd / totalNoComb
    // FIX-004: MSD reduced from 0.40→0.33, effective 42.1% → 34.7%
    expect(effectiveMsd).toBeCloseTo(0.347, 2)
  })

  it('MUSIC Phase effective weight is 38.0%', () => {
    const w = FUSION_WEIGHTS.MUSIC
    const totalNoComb = 1 - w.comb
    const effectivePhase = w.phase / totalNoComb
    expect(effectivePhase).toBeCloseTo(0.380, 2)
  })

  it('COMPRESSED Phase effective weight is ~32.6% (FIX-005: reduced from 41.3%)', () => {
    const w = FUSION_WEIGHTS.COMPRESSED
    const totalNoComb = 1 - w.comb
    const effectivePhase = w.phase / totalNoComb
    // FIX-005: phase reduced from 0.38 → 0.30, effective 41.3% → 32.6%
    expect(effectivePhase).toBeCloseTo(0.326, 2)
  })

  it('MUSIC existing effective weight is 5.4%', () => {
    const w = FUSION_WEIGHTS.MUSIC
    const totalNoComb = 1 - w.comb
    const effectiveExisting = w.existing / totalNoComb
    // FIX-002: existing reduced from 0.15 → 0.05, effective 16.3% → 5.4%
    expect(effectiveExisting).toBeCloseTo(0.054, 2)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 3. SINGLE-ALGORITHM ISOLATION — No algorithm alone should reach FEEDBACK
//
// With all other algorithms at score=0 and existingScore=0, a single
// algorithm at max cannot accumulate enough weight to cross the threshold.
// ═════════════════════════════════════════════════════════════════════════════

describe('Single-Algorithm Isolation', () => {
  it('MSD=1.0 alone cannot reach FEEDBACK (probability < 0.35)', () => {
    const result = fuse(
      { msd: 1.0, phase: 0, spectral: 0, comb: 0, ihr: 0, ptmr: 0 },
      'unknown',
      0 // existingScore = 0
    )
    expect(result.feedbackProbability).toBeLessThan(0.35)
  })

  it('MSD+Phase both=1.0 still below FEEDBACK threshold (< 0.60)', () => {
    const result = fuse(
      { msd: 1.0, phase: 1.0, spectral: 0, comb: 0, ihr: 0, ptmr: 0 },
      'unknown',
      0
    )
    expect(result.feedbackProbability).toBeLessThan(0.60)
  })

  it('MSD+Phase+Spectral all=1.0 exceeds 0.60 (with PTMR support)', () => {
    // ADV-001: ptmr=0 now triggers PTMR breadth gate (×0.80), so provide
    // minimal PTMR support to avoid penalty
    const result = fuse(
      { msd: 1.0, phase: 1.0, spectral: 1.0, comb: 0, ihr: 0, ptmr: 0.3 },
      'unknown',
      0
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 4. GEMINI VULNERABILITY SCENARIOS — CURRENT WEIGHTS
//
// These document KNOWN vulnerabilities in the current weight profiles.
// When weights are improved, update the expected verdicts accordingly.
// ═════════════════════════════════════════════════════════════════════════════

describe('Gemini Vulnerability Scenarios — DEFAULT Profile', () => {
  /**
   * Scenario: Sustained synthesizer note
   * Flat envelope (MSD=0.8), highly tonal (Phase=0.9), rich harmonics (IHR=0.1),
   * moderate flatness (Spectral=0.4), prominent (PTMR=0.7, Existing=0.8).
   * No comb pattern.
   *
   * EXPECTED: FALSE POSITIVE — music incorrectly classified as feedback.
   * Gemini calculated: 0.650 (above 0.60 threshold)
   */
  it('FALSE POSITIVE: sustained synth note scores above threshold', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.9, spectral: 0.4, comb: 0, ihr: 0.1, ptmr: 0.7 },
      'unknown',
      0.8 // existing score
    )
    // Document the vulnerability: this SHOULD be NOT_FEEDBACK or UNCERTAIN
    // but with current weights it exceeds the threshold
    expect(result.feedbackProbability).toBeGreaterThan(0.55)
    // The exact verdict depends on confidence calculation too
    console.log(`[DEFAULT FP] synth note: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })

  /**
   * Scenario: Low-frequency feedback in reverberant room
   * Slow MSD growth (MSD=0.4), smeared phase (Phase=0.5), pure tone
   * (Spectral=0.9, IHR=0.9, PTMR=0.8), prominent (Existing=0.9). No comb.
   *
   * EXPECTED: FALSE NEGATIVE — real feedback missed.
   * Gemini calculated: 0.571 (below 0.60 threshold)
   */
  it('FALSE NEGATIVE: low-freq reverberant feedback scores below threshold', () => {
    const result = fuse(
      { msd: 0.4, phase: 0.5, spectral: 0.9, comb: 0, ihr: 0.9, ptmr: 0.8 },
      'unknown',
      0.9
    )
    expect(result.feedbackProbability).toBeLessThan(0.65)
    console.log(`[DEFAULT FN] reverberant feedback: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

describe('Gemini Vulnerability Scenarios — SPEECH Profile', () => {
  /**
   * Scenario: Speaker holding a long vowel "Ummmm" into compressed mic
   * Stable amplitude (MSD=0.9), highly tonal (Phase=0.8), complex harmonics
   * (IHR=0.2, Spectral=0.5), prominent (PTMR=0.6, Existing=0.7).
   *
   * EXPECTED: FALSE POSITIVE — speech incorrectly classified as feedback.
   * Gemini calculated: 0.710 (well above threshold)
   * ROOT CAUSE: MSD weight of 0.40 makes any stable amplitude trigger detection.
   */
  it('FALSE POSITIVE: sustained vowel scores well above threshold', () => {
    const result = fuse(
      { msd: 0.9, phase: 0.8, spectral: 0.5, comb: 0, ihr: 0.2, ptmr: 0.6 },
      'speech',
      0.7
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
    console.log(`[SPEECH FP] sustained vowel: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })

  /**
   * Scenario: Fast ringing feedback clamped by system limiter
   * Zero growth (MSD=0.1), perfect tone (Phase=0.9, Spectral=0.9, IHR=0.9,
   * PTMR=0.9), prominent (Existing=0.8).
   *
   * EXPECTED: FALSE NEGATIVE — real feedback missed because limiter kills MSD.
   * Gemini calculated: 0.525 (below threshold)
   * ROOT CAUSE: MSD weight of 0.40 means zero-growth feedback can't compensate.
   */
  it('FALSE NEGATIVE: limiter-clamped feedback scores below threshold', () => {
    const result = fuse(
      { msd: 0.1, phase: 0.9, spectral: 0.9, comb: 0, ihr: 0.9, ptmr: 0.9 },
      'speech',
      0.8
    )
    expect(result.feedbackProbability).toBeLessThan(0.65)
    console.log(`[SPEECH FN] limiter-clamped: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

describe('Gemini Vulnerability Scenarios — MUSIC Profile', () => {
  /**
   * Scenario: Intentional musical guitar feedback
   * Flat envelope (MSD=0.8), perfectly coherent (Phase=0.95), some harmonics
   * (IHR=0.2, Spectral=0.6), very prominent (PTMR=0.8, Existing=0.9).
   *
   * EXPECTED: FALSE POSITIVE — but arguably correct, since intentional
   * feedback IS acoustically identical to unwanted feedback.
   * Gemini calculated: 0.711
   */
  it('FALSE POSITIVE: intentional guitar feedback (expected and acceptable)', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.95, spectral: 0.6, comb: 0, ihr: 0.2, ptmr: 0.8 },
      'music',
      0.9
    )
    // This false positive is arguably CORRECT behavior —
    // intentional feedback IS feedback. Documenting, not fixing.
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
    console.log(`[MUSIC FP] guitar feedback: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })

  /**
   * Scenario: Unwanted feedback hidden in dense loud mix
   * Phase ruined by mix masking (Phase=0.3), slowly growing (MSD=0.6),
   * pure tone in FFT gap (Spectral=0.8, IHR=0.8, PTMR=0.7), Existing=0.6.
   *
   * EXPECTED: FALSE NEGATIVE — real feedback missed in dense mix.
   * Gemini calculated: 0.496 (well below threshold)
   * ROOT CAUSE: Phase weight of 0.35 means dense mixes that mask phase cause failure.
   */
  it('FALSE NEGATIVE: feedback hidden in dense mix', () => {
    const result = fuse(
      { msd: 0.6, phase: 0.3, spectral: 0.8, comb: 0, ihr: 0.8, ptmr: 0.7 },
      'music',
      0.6
    )
    expect(result.feedbackProbability).toBeLessThan(0.60)
    console.log(`[MUSIC FN] dense mix: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

describe('Gemini Vulnerability Scenarios — COMPRESSED Profile', () => {
  /**
   * Scenario: Compressed backing track with clean flute sample
   * Slight growth (MSD=0.5), perfectly tonal (Phase=0.95), moderate purity
   * (Spectral=0.6, IHR=0.3, PTMR=0.6), prominent (Existing=0.8).
   *
   * EXPECTED: FALSE POSITIVE — clean flute classified as feedback.
   * Gemini calculated: 0.663
   */
  it('FALSE POSITIVE: compressed flute sample scores above threshold', () => {
    const result = fuse(
      { msd: 0.5, phase: 0.95, spectral: 0.6, comb: 0, ihr: 0.3, ptmr: 0.6, compressed: true },
      'unknown', // contentType doesn't matter when compressed=true
      0.8
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.55)
    console.log(`[COMPRESSED FP] flute: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })

  /**
   * Scenario: Feedback fighting against heavy mix bus compressor
   * Compressor pumping randomizes phase (Phase=0.2), growing amplitude
   * (MSD=0.8), pure tone underneath (Spectral=0.8, IHR=0.9, PTMR=0.8),
   * Existing=0.7.
   *
   * PRE-FIX-005: FALSE NEGATIVE — real feedback missed because compressor
   * destroyed the very signal (phase) that COMPRESSED mode relied on most.
   * Gemini calculated: 0.508. ROOT CAUSE: Phase weight of 0.38 was a
   * single point of failure.
   *
   * POST-FIX-005: IMPROVED — redistributing phase weight to spectral/ihr/ptmr
   * means the strong non-phase signals (spectral=0.8, ihr=0.9, ptmr=0.8)
   * now carry enough weight to cross the threshold. Real feedback detected!
   */
  it('FN IMPROVED: compressor-pumped feedback now detected (FIX-005)', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.2, spectral: 0.8, comb: 0, ihr: 0.9, ptmr: 0.8, compressed: true },
      'unknown',
      0.7
    )
    // FIX-005: phase redistribution allows non-phase algorithms to detect.
    // Prob crosses 0.60 but compressed thresholdMultiplier (1.5) raises
    // FEEDBACK threshold to 0.90, so verdict stays POSSIBLE_FEEDBACK.
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
    expect(result.verdict).toBe('POSSIBLE_FEEDBACK')
    console.log(`[COMPRESSED FN IMPROVED] pumping: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 5. THREE-MODEL CONSENSUS VULNERABILITY SCENARIOS (TEST-004)
//
// 8 scenarios from cross-validation audit. These document CURRENT behavior
// as a regression baseline — they are NOT desired behavior.
// ═════════════════════════════════════════════════════════════════════════════

describe('Consensus Vulnerability: DEFAULT Profile', () => {
  it('V1 — FP: Synth note (MSD+Phase dominant)', () => {
    const result = fuse(
      { msd: 0.85, phase: 0.80, spectral: 0.55, ihr: 0.20, ptmr: 0.35, comb: 0 },
      'unknown',
      0.80
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
    console.log(`[V1 DEFAULT FP] synth: prob=${result.feedbackProbability.toFixed(3)}, conf=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })

  it('V2 — FN: Spectral-only feedback (MSD+Phase blind)', () => {
    const result = fuse(
      { msd: 0, phase: 0, spectral: 0.80, ihr: 0.80, ptmr: 0.80, comb: 0 },
      'unknown',
      0.20
    )
    expect(result.feedbackProbability).toBeLessThan(0.35)
    console.log(`[V2 DEFAULT FN] spectral-only: prob=${result.feedbackProbability.toFixed(3)}, conf=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

describe('Consensus Vulnerability: SPEECH Profile', () => {
  it('V3 — FP FIXED: MSD-only conviction no longer reaches FEEDBACK (FIX-004)', () => {
    const result = fuse(
      { msd: 1.0, phase: 0, spectral: 0.60, ihr: 0.40, ptmr: 0.60, comb: 0 },
      'speech',
      0.80
    )
    // FIX-004: SPEECH MSD reduced from 0.40→0.33.
    // Before: prob=0.634 (FEEDBACK). After: prob≈0.579 (POSSIBLE_FEEDBACK).
    // MSD-only conviction no longer crosses the 0.60 threshold.
    expect(result.feedbackProbability).toBeLessThan(0.60)
    expect(result.verdict).not.toBe('FEEDBACK')
    console.log(`[V3 SPEECH FP FIXED] msd-only: prob=${result.feedbackProbability.toFixed(3)}, conf=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })

  it('V4 — FN: No MSD (feedback invisible to dominant algorithm)', () => {
    const result = fuse(
      { msd: 0, phase: 0.20, spectral: 0.80, ihr: 0.80, ptmr: 0.80, comb: 0 },
      'speech',
      0
    )
    expect(result.feedbackProbability).toBeLessThan(0.35)
    console.log(`[V4 SPEECH FN] no-msd: prob=${result.feedbackProbability.toFixed(3)}, conf=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

describe('Consensus Vulnerability: MUSIC Profile', () => {
  it('V5 — FP: Phase-dominant (phase alone convicts)', () => {
    const result = fuse(
      { msd: 0, phase: 1.0, spectral: 0.80, ihr: 0.60, ptmr: 0.40, comb: 0 },
      'music',
      0.80
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
    console.log(`[V5 MUSIC FP] phase-dominant: prob=${result.feedbackProbability.toFixed(3)}, conf=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })

  it('V6 — FN: No phase (feedback invisible to dominant algorithm)', () => {
    const result = fuse(
      { msd: 0.80, phase: 0, spectral: 0.80, ihr: 0.80, ptmr: 0.20, comb: 0 },
      'music',
      0
    )
    expect(result.feedbackProbability).toBeLessThan(0.40)
    console.log(`[V6 MUSIC FN] no-phase: prob=${result.feedbackProbability.toFixed(3)}, conf=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

describe('Consensus Vulnerability: COMB Pattern', () => {
  it('V7 — Comb flip: same scores, comb presence crosses threshold', () => {
    const scores = { msd: 0.60, phase: 0.60, spectral: 0.60, ihr: 0.60, ptmr: 0.60, comb: 0 }

    const noComb = fuse(scores, 'unknown', 0.40)
    expect(noComb.feedbackProbability).toBeLessThan(0.60)

    const withComb = fuse({ ...scores, comb: 0.80 }, 'unknown', 0.40)
    expect(withComb.feedbackProbability).toBeGreaterThan(0.60)

    console.log(`[V7 COMB] noComb=${noComb.feedbackProbability.toFixed(3)}, withComb=${withComb.feedbackProbability.toFixed(3)}, delta=${(withComb.feedbackProbability - noComb.feedbackProbability).toFixed(3)}`)
  })
})

describe('Consensus Vulnerability: COMPRESSED Profile', () => {
  it('V8 — FP FIXED: Phase conviction under compression no longer reaches FEEDBACK (FIX-005)', () => {
    const result = fuse(
      { msd: 0, phase: 1.0, spectral: 0.40, ihr: 0.40, ptmr: 0.60, compressed: true, comb: 0 },
      'unknown',
      0.80
    )
    // FIX-005: COMPRESSED phase reduced 0.38→0.30, prob drops below 0.60
    expect(result.feedbackProbability).toBeLessThan(0.60)
    expect(result.verdict).not.toBe('FEEDBACK')
    console.log(`[V8 COMPRESSED FP FIXED] phase-conviction: prob=${result.feedbackProbability.toFixed(3)}, conf=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 6. BASELINE SCENARIOS — Known Ground Truth
// ═════════════════════════════════════════════════════════════════════════════

describe('Baseline: Obvious Cases', () => {
  it('Pure feedback: all algorithms agree → FEEDBACK', () => {
    const result = fuse(
      { msd: 0.95, phase: 0.95, spectral: 0.95, comb: 0, ihr: 0.95, ptmr: 0.95 },
      'unknown',
      0.95
    )
    expect(result.verdict).toBe('FEEDBACK')
    expect(result.feedbackProbability).toBeGreaterThan(0.90)
    expect(result.confidence).toBeGreaterThan(0.80)
  })

  it('Pure music: all algorithms agree → low probability', () => {
    const result = fuse(
      { msd: 0.05, phase: 0.1, spectral: 0.05, comb: 0, ihr: 0.05, ptmr: 0.05 },
      'music',
      0.1
    )
    // Verdict may be NOT_FEEDBACK or UNCERTAIN depending on confidence;
    // the key assertion is that probability stays well below threshold.
    expect(result.feedbackProbability).toBeLessThan(0.15)
    expect(result.verdict).not.toBe('FEEDBACK')
  })

  it('Silence: no algorithm data → low probability', () => {
    const result = fuse(
      {}, // All null
      'unknown',
      0.5
    )
    // Only 'existing' contributes with score 0.5
    expect(result.feedbackProbability).toBeLessThan(0.55)
  })

  it('Feedback with comb pattern: comb doubles weight and boosts score', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.85, spectral: 0.7, comb: 0.9, ihr: 0.8, ptmr: 0.8 },
      'unknown',
      0.7
    )
    expect(result.verdict).toBe('FEEDBACK')
    expect(result.contributingAlgorithms).toContain('Comb')
    // Comb should increase total probability
    const noComb = fuse(
      { msd: 0.8, phase: 0.85, spectral: 0.7, comb: 0, ihr: 0.8, ptmr: 0.8 },
      'unknown',
      0.7
    )
    expect(result.feedbackProbability).toBeGreaterThan(noComb.feedbackProbability)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 7. EDGE CASES
// ═════════════════════════════════════════════════════════════════════════════

describe('Edge Cases', () => {
  /**
   * DA-004: Confidence warmup penalty
   * When only MSD has data and other algorithms are null, the confidence
   * calculation should not penalize a strong single-algorithm detection.
   */
  it('DA-004: single strong MSD should still reach POSSIBLE_FEEDBACK', () => {
    const result = fuse(
      { msd: 0.9, msdFrames: 15 },
      'speech',
      0.5
    )
    // With only MSD (0.9) and existing (0.5), we want at least POSSIBLE_FEEDBACK
    // Current behavior: confidence may be too low due to variance between 0.9 and 0.5
    console.log(`[DA-004] MSD-only: probability=${result.feedbackProbability.toFixed(3)}, confidence=${result.confidence.toFixed(3)}, verdict=${result.verdict}`)
    // At minimum, probability should reflect the strong MSD signal
    expect(result.feedbackProbability).toBeGreaterThan(0.5)
  })

  it('Content type selects correct weight profile', () => {
    const scores = { msd: 0.5, phase: 0.5, spectral: 0.5, comb: 0, ihr: 0.5, ptmr: 0.5 }

    const speech = fuse(scores, 'speech', 0.5)
    const music = fuse(scores, 'music', 0.5)

    // SPEECH weights MSD at 0.40, MUSIC at 0.15
    // With same feedbackScores, SPEECH should produce higher probability
    // because MSD (0.5) * 0.40 > MSD (0.5) * 0.15 only matters when
    // combined with other weights. All scores equal means probability ≈ 0.5 for both.
    // But the weight distribution differences still create slight variations.
    expect(speech.feedbackProbability).toBeCloseTo(0.5, 1)
    expect(music.feedbackProbability).toBeCloseTo(0.5, 1)
  })

  it('Compressed audio triggers COMPRESSED weight profile', () => {
    const result = fuse(
      { msd: 0.5, phase: 0.5, spectral: 0.5, comb: 0, ihr: 0.5, ptmr: 0.5, compressed: true },
      'speech', // Content type is overridden by compressed detection
      0.5
    )
    expect(result.reasons.some(r => r.includes('Compression detected'))).toBe(true)
  })

  it('Algorithm mode "msd" only uses MSD + IHR + PTMR + existing', () => {
    const result = fuse(
      { msd: 0.9, phase: 0.9, spectral: 0.9, comb: 0.9, ihr: 0.9, ptmr: 0.9 },
      'unknown',
      0.9,
      { mode: 'msd' }
    )
    expect(result.contributingAlgorithms).toContain('MSD')
    expect(result.contributingAlgorithms).not.toContain('Phase')
    expect(result.contributingAlgorithms).not.toContain('Spectral')
    expect(result.contributingAlgorithms).not.toContain('Comb')
  })

  it('Algorithm mode "phase" excludes MSD', () => {
    const result = fuse(
      { msd: 0.9, phase: 0.9, spectral: 0.9, comb: 0.9, ihr: 0.9, ptmr: 0.9 },
      'unknown',
      0.9,
      { mode: 'phase' }
    )
    expect(result.contributingAlgorithms).not.toContain('MSD')
    expect(result.contributingAlgorithms).toContain('Phase')
  })

  it('feedbackProbability is always in [0, 1]', () => {
    // Extreme high scores
    const high = fuse(
      { msd: 1.0, phase: 1.0, spectral: 1.0, comb: 1.0, ihr: 1.0, ptmr: 1.0 },
      'unknown',
      1.0
    )
    expect(high.feedbackProbability).toBeLessThanOrEqual(1.0)
    expect(high.feedbackProbability).toBeGreaterThanOrEqual(0.0)

    // Extreme low scores
    const low = fuse(
      { msd: 0.0, phase: 0.0, spectral: 0.0, comb: 0, ihr: 0.0, ptmr: 0.0 },
      'unknown',
      0.0
    )
    expect(low.feedbackProbability).toBeLessThanOrEqual(1.0)
    expect(low.feedbackProbability).toBeGreaterThanOrEqual(0.0)
  })

  it('Verdict thresholds are correct', () => {
    // FEEDBACK requires probability >= 0.60 AND confidence >= 0.6
    // POSSIBLE_FEEDBACK requires probability >= 0.42 AND confidence >= 0.4
    // NOT_FEEDBACK requires probability < 0.3 AND confidence >= 0.6

    const feedback = fuse(
      { msd: 0.95, phase: 0.95, spectral: 0.95, comb: 0, ihr: 0.95, ptmr: 0.95 },
      'unknown',
      0.95
    )
    expect(feedback.verdict).toBe('FEEDBACK')

    const notFeedback = fuse(
      { msd: 0.02, phase: 0.05, spectral: 0.02, comb: 0, ihr: 0.02, ptmr: 0.02 },
      'unknown',
      0.05
    )
    // Low scores yield low probability; verdict is NOT_FEEDBACK or UNCERTAIN
    // depending on confidence (variance between small values reduces agreement).
    expect(notFeedback.feedbackProbability).toBeLessThan(0.10)
    expect(notFeedback.verdict).not.toBe('FEEDBACK')
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 8. LOW-FREQUENCY PHASE SUPPRESSION (ADV-002)
// ═════════════════════════════════════════════════════════════════════════════

describe('Low-Frequency Phase Suppression (ADV-002)', () => {
  const highPhaseScores = { msd: 0.5, phase: 1.0, spectral: 0.5, comb: 0, ihr: 0.5, ptmr: 0.5 }

  it('phase is suppressed at 100 Hz (below 200 Hz threshold)', () => {
    const normal = fuse(highPhaseScores, 'unknown', 0.5, undefined, undefined)
    const lowFreq = fuse(highPhaseScores, 'unknown', 0.5, undefined, 100)

    // Low-frequency version should have lower probability due to phase × 0.5
    expect(lowFreq.feedbackProbability).toBeLessThan(normal.feedbackProbability)
    console.log(`[ADV-002] normal=${normal.feedbackProbability.toFixed(3)}, lowFreq=${lowFreq.feedbackProbability.toFixed(3)}`)
  })

  it('phase is NOT suppressed at 500 Hz (above 200 Hz threshold)', () => {
    const normal = fuse(highPhaseScores, 'unknown', 0.5, undefined, undefined)
    const midFreq = fuse(highPhaseScores, 'unknown', 0.5, undefined, 500)

    // Above 200 Hz: no suppression, same probability
    expect(midFreq.feedbackProbability).toBeCloseTo(normal.feedbackProbability, 10)
  })

  it('phase is NOT suppressed when peakFrequencyHz is undefined', () => {
    const withoutFreq = fuse(highPhaseScores, 'unknown', 0.5, undefined, undefined)
    const withHighFreq = fuse(highPhaseScores, 'unknown', 0.5, undefined, 1000)

    // Both should be identical: no suppression
    expect(withoutFreq.feedbackProbability).toBeCloseTo(withHighFreq.feedbackProbability, 10)
  })

  it('suppression at 50 Hz reduces phase influence significantly', () => {
    // Use MUSIC profile where phase is dominant (35% weight)
    const normal = fuse(highPhaseScores, 'music', 0.5, undefined, undefined)
    const subBass = fuse(highPhaseScores, 'music', 0.5, undefined, 50)

    const delta = normal.feedbackProbability - subBass.feedbackProbability
    // Phase score halved × 35% nominal weight → expect noticeable drop
    expect(delta).toBeGreaterThan(0.05)
    console.log(`[ADV-002 MUSIC] delta=${delta.toFixed(3)} (normal=${normal.feedbackProbability.toFixed(3)}, subBass=${subBass.feedbackProbability.toFixed(3)})`)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 9. PROPOSED V2 WEIGHTS — Regression Tests
//
// When implementing weight changes based on Gemini's recommendations,
// uncomment these tests and update the expected values.
// ═════════════════════════════════════════════════════════════════════════════

describe.skip('Proposed V2 Weights — Regression Tests', () => {
  // V2 weights based on Gemini analysis + Claude audit:
  // SPEECH_V2:   msd:0.35, phase:0.20, spectral:0.10, comb:0.05, ihr:0.10, ptmr:0.15, existing:0.05
  // MUSIC_V2:    msd:0.05, phase:0.30, spectral:0.12, comb:0.10, ihr:0.18, ptmr:0.15, existing:0.10
  // COMPRESS_V2: msd:0.08, phase:0.30, spectral:0.15, comb:0.10, ihr:0.15, ptmr:0.12, existing:0.10
  // DEFAULT_V2:  msd:0.25, phase:0.22, spectral:0.12, comb:0.08, ihr:0.13, ptmr:0.12, existing:0.08
  //
  // Note: customWeights uses Partial<typeof FUSION_WEIGHTS.DEFAULT> which has
  // literal types from `as const`. Cast to number to allow proposed values.
  type W = Record<string, number>

  it('V2 SPEECH: sustained vowel no longer false positive', () => {
    const result = fuse(
      { msd: 0.9, phase: 0.8, spectral: 0.5, comb: 0, ihr: 0.2, ptmr: 0.6 },
      'speech',
      0.7,
      { customWeights: { msd: 0.35, phase: 0.20, spectral: 0.10, comb: 0.05, ihr: 0.10, ptmr: 0.15, existing: 0.05 } as W }
    )
    // With V2 weights, this should score BELOW threshold
    expect(result.feedbackProbability).toBeLessThan(0.60)
    console.log(`[V2 SPEECH FP] sustained vowel: probability=${result.feedbackProbability.toFixed(3)}, verdict=${result.verdict}`)
  })

  it('V2 SPEECH: limiter-clamped feedback now detected', () => {
    const result = fuse(
      { msd: 0.1, phase: 0.9, spectral: 0.9, comb: 0, ihr: 0.9, ptmr: 0.9 },
      'speech',
      0.8,
      { customWeights: { msd: 0.35, phase: 0.20, spectral: 0.10, comb: 0.05, ihr: 0.10, ptmr: 0.15, existing: 0.05 } as W }
    )
    // With V2 weights, PTMR at 0.15 and IHR at 0.10 should compensate for low MSD
    console.log(`[V2 SPEECH FN] limiter-clamped: probability=${result.feedbackProbability.toFixed(3)}, verdict=${result.verdict}`)
  })

  it('V2 MUSIC: feedback in dense mix now detected', () => {
    const result = fuse(
      { msd: 0.6, phase: 0.3, spectral: 0.8, comb: 0, ihr: 0.8, ptmr: 0.7 },
      'music',
      0.6,
      { customWeights: { msd: 0.05, phase: 0.30, spectral: 0.12, comb: 0.10, ihr: 0.18, ptmr: 0.15, existing: 0.10 } as W }
    )
    // With V2 weights, IHR at 0.18 and PTMR at 0.15 should push this above threshold
    console.log(`[V2 MUSIC FN] dense mix: probability=${result.feedbackProbability.toFixed(3)}, verdict=${result.verdict}`)
  })

  it('V2 COMPRESSED: compressor-pumped feedback now detected', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.2, spectral: 0.8, comb: 0, ihr: 0.9, ptmr: 0.8, compressed: true },
      'unknown',
      0.7,
      { customWeights: { msd: 0.08, phase: 0.30, spectral: 0.15, comb: 0.10, ihr: 0.15, ptmr: 0.12, existing: 0.10 } as W }
    )
    // With V2 weights, reduced phase dependency and increased IHR/spectral
    // should detect feedback even when phase is ruined by compressor pumping
    console.log(`[V2 COMPRESSED FN] pumping: probability=${result.feedbackProbability.toFixed(3)}, verdict=${result.verdict}`)
  })
})
